### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ClosetMonkey** [snowem/snowem#8]
What is the current status of this project? Which browsers have you tested it with? Do you plan on continuing development? Thanks

**Comment by jackiedinh8** [comment]
It has been tested with chrome browser. I have a plan at least on developing the followings: support unified plan and other basic features like stun/turn, tcp connections, etc. Another thinking is to build it as a micro service, which means it can be used for only video streaming and leave stream management to external service (think of conference room management).

**Comment by ClosetMonkey** [comment]
approximately how much memory an inactive instance require?

**Comment by jackiedinh8** [comment]
pre-allocation memory strategy is used here, it's about 200 Mb.
